---
name: Build

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    name: "Ubuntu with clang ${{ matrix.clang-version }}"
    runs-on: ubuntu-latest
    container: ubuntu:25.10
    strategy:
      matrix:
        clang-version:
          - 19
          - 20
          - 21

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          apt update
          apt -y install \
            cmake \
            zip \
            libstdc++-15-dev \
            clang-${{ matrix.clang-version }} \
            libclang-${{ matrix.clang-version }}-dev \
            clang-tidy-${{ matrix.clang-version }} \
            llvm-${{ matrix.clang-version }}-dev \
            llvm-${{ matrix.clang-version }}-tools

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_C_COMPILER=/usr/bin/clang-${{matrix.clang-version}} \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${{matrix.clang-version}} \
            -DCMAKE_PREFIX_PATH=/usr/lib/llvm-${{matrix.clang-version}} \
            -DBUILD_TESTING=On \
            ..
          make -j"$(nproc)" check-chatterino-clang-tidy-module

      - name: Generate tag
        id: gen-tag
        run: echo "name=chatterino-clang-tidy-module-clang${{ matrix.clang-version }}" >> "$GITHUB_OUTPUT"

      - name: Prepare artifact
        run: |
          cp build/src/chatterino-clang-tidy-module.so chatterino-clang-tidy-module-${{ matrix.clang-version }}.so
          zip -r "${{ steps.gen-tag.outputs.name }}.zip" chatterino-clang-tidy-module-${{ matrix.clang-version }}.so

      - name: Create release
        uses: ncipollo/release-action@v1.20.0
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.gen-tag.outputs.name }}.zip
          body: ""
          prerelease: true
          name: Chatterino clang-tidy-module
          tag: ci
